### ISSUE TITLE
Cannot add direct to cart from product list once Packages are defined

### ISSUE THREAD

**Issue by ProxiBlue** [enanobots/m2-product-pack#2]
Once packages are defined on a product, 'add to cart' for normal usage no longer works from product list.

![image](https://user-images.githubusercontent.com/4994260/218244655-b0477091-5f9c-4a90-bf07-3f3d2e8aec8c.png)

**Comment by enanobots** [comment]
@ProxiBlue pushed code update to 1.0.4, required few more changes to type renderers
