### ISSUE TITLE
Attributes with apply_to set (for simples) disappear when product type is set to pack.

### ISSUE THREAD

**Issue by ProxiBlue** [enanobots/m2-product-pack#8]
Tested with 

Magento 2.4.4-p6
Pack module 1.1.0

Some attributes can be set to apply to 'a set of product types''
On a default install, it seems to already be a few out the box

```
SELECT distinct cea.attribute_id, cea.apply_to, ea.attribute_code 
FROM catalog_eav_attribute AS cea
LEFT JOIN eav_attribute AS ea ON cea.attribute_id = ea.attribute_id
WHERE apply_to LIKE '%simple,%'
```
![image](https://github.com/enanobots/m2-product-pack/assets/4994260/51289016-a96f-4485-91e1-0a181d6fa35e)

Testing: Product as simple:

![image](https://github.com/enanobots/m2-product-pack/assets/4994260/3416e810-30e9-4b95-85bc-9ccc0e8bbdb1)

which displays the attribute 'manufacturer' (which is in the above list)

![image](https://github.com/enanobots/m2-product-pack/assets/4994260/19390aa8-d217-4667-aeab-18c0b6537efd)

as well as 'price' 

![image](https://github.com/enanobots/m2-product-pack/assets/4994260/1dae2cf5-4cc9-4800-b5e3-37f3dc50ea18)

** Changed product now to pack by setting pack options

![image](https://github.com/enanobots/m2-product-pack/assets/4994260/47eedb40-e7d1-4ebd-8c90-da71de88cfc3)

Missing attributes on product edit (now it is a pack)

![image](https://github.com/enanobots/m2-product-pack/assets/4994260/f436e293-9e5f-4e29-bec0-2378cb6d5bfc)

manufacturer is also misisng

![image](https://github.com/enanobots/m2-product-pack/assets/4994260/3c73ba0f-2e2e-44be-9ed9-497028345f83)

If I adjust the db, to include Pack as one of the 'apply_to' types, the issue seems resolved.

```
SELECT DISTINCT concat('UPDATE catalog_eav_attribute SET apply_to = \'',apply_to,',pack\' WHERE apply_to =\'',apply_to,'\'') FROM catalog_eav_attribute where apply_to like '%simple,%'
```

```
UPDATE catalog_eav_attribute SET apply_to = 'simple,virtual,downloadable,bundle,configurable,pack' WHERE apply_to ='simple,virtual,downloadable,bundle,configurable'
UPDATE catalog_eav_attribute SET apply_to = 'simple,virtual,downloadable,pack' WHERE apply_to ='simple,virtual,downloadable'
UPDATE catalog_eav_attribute SET apply_to = 'simple,configurable,pack' WHERE apply_to ='simple,configurable'
UPDATE catalog_eav_attribute SET apply_to = 'simple,virtual,downloadable,bundle,pack' WHERE apply_to ='simple,virtual,downloadable,bundle'
UPDATE catalog_eav_attribute SET apply_to = 'simple,virtual,configurable,pack' WHERE apply_to ='simple,virtual,configurable'
UPDATE catalog_eav_attribute SET apply_to = 'simple,bundle,grouped,configurable,pack' WHERE apply_to ='simple,bundle,grouped,configurable'
```

![image](https://github.com/enanobots/m2-product-pack/assets/4994260/ccae97d5-447e-4a5e-bb6b-583d4e931867)

It would seem to me we are missing 3 things:

1. Install: Insert 'pack' as a type into any existing entries with 'simple' listed.
2. Reverse 1 on uninstall
3. How will dealing with other 3rd party modules that set apply_to work? If any future installed modules set apply_to, we will need to intercept that save, and inject pack if simple is in save value. Or is there a built in way already?

**Comment by qsolutions-pl** [comment]
code merged, new tag created 1.0.7
